name: Multi-OS Electron-Build using Forge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: "npm install"
      - name: Install Angular CLI
        run: "npm install -g @angular/cli"
      - name: Build Angular App
        run: "npm run build"
      - name: Run electron-forge to build the bundle
        run: "npm run make"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: out/make/
