name: Create runnable JARs
on:
  push:
    branches: [main]

jobs:
  jar-create:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@1.4.4
        with:
          java-version: 17
      - name: Run package
        run: mvn -Djar.finalName=dmt-${{matrix.os}} package
      - name: actions/upload-artifact@v3
        with:
          name: jars
          path: ./target/dmt-${{matrix.os}}.jar
      
  
